package com.w2sv.filenavigator.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00696E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6FF6FE)
val md_theme_light_onPrimaryContainer = Color(0xFF002021)
val md_theme_light_secondary = Color(0xFF006B5C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF09FEDD)
val md_theme_light_onSecondaryContainer = Color(0xFF00201B)
val md_theme_light_tertiary = Color(0xFF8C4381)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD7F2)
val md_theme_light_onTertiaryContainer = Color(0xFF390035)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFC)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFFAFDFC)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFDAE4E5)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4949)
val md_theme_light_outline = Color(0xFF6F7979)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inversePrimary = Color(0xFF4CD9E1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00696E)
val md_theme_light_outlineVariant = Color(0xFFBEC8C9)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_onPrimary = Color(0xFF003739)
val md_theme_dark_primaryContainer = Color(0xFF004F53)
val md_theme_dark_onPrimaryContainer = Color(0xFF6FF6FE)
val md_theme_dark_primary = md_theme_light_primary
val md_theme_dark_secondary = Color(0xFF00DFC2)
val md_theme_dark_onSecondary = Color(0xFF00382F)
val md_theme_dark_secondaryContainer = Color(0xFF005045)
val md_theme_dark_onSecondaryContainer = Color(0xFF09FEDD)
val md_theme_dark_tertiary = Color(0xFFFFACEC)
val md_theme_dark_onTertiary = Color(0xFF56124F)
val md_theme_dark_tertiaryContainer = Color(0xFF712B67)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD7F2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E3)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF3F4949)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C9)
val md_theme_dark_outline = Color(0xFF899393)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E3)
val md_theme_dark_inversePrimary = Color(0xFF00696E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4CD9E1)
val md_theme_dark_outlineVariant = Color(0xFF3F4949)
val md_theme_dark_scrim = Color(0xFF000000)

val md_positive = Color(12, 173, 34, 200)
val md_negative = Color(201, 14, 52, 200)

@Composable
fun disabledColor(): Color = MaterialTheme.colorScheme.onSurface.copy(0.38f)